In [211]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import keras
from keras.models import Sequential 
from keras.layers import Dense
from sklearn.metrics import accuracy_score
#KFolds
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

In [152]:
dataset = pd.read_csv("D:/Jhonnatan/Documents/MAESTRIA DATA SCIENCE/3er Trimestre/Statical Learning III/TAREAS/titanic/train.csv")

In [153]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [154]:
dataset.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [155]:
dataset = dataset[["Survived", "Pclass", "Sex", "Age", "SibSp","Parch", "Embarked"]]

In [156]:
#verificacion de NAs
dataset.isnull().values.any()

True

In [157]:
dataset.head()

Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0       3    male  22.0      1      0        S
1         1       1  female  38.0      1      0        C
2         1       3  female  26.0      0      0        S
3         1       1  female  35.0      1      0        S
4         0       3    male  35.0      0      0        S

In [158]:
moda_edad = dataset.mode()
moda_edad[["Age"]]

Age
0  24.0

In [159]:
dataset = dataset.fillna(24)

In [160]:
dataset = dataset[dataset.Age.notnull()]
dataset.head()

Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0       3    male  22.0      1      0        S
1         1       1  female  38.0      1      0        C
2         1       3  female  26.0      0      0        S
3         1       1  female  35.0      1      0        S
4         0       3    male  35.0      0      0        S

In [161]:
ohe = pd.get_dummies(dataset['Sex'],drop_first = True)
dataset.drop('Sex', axis = 1, inplace = True)
dataset =  dataset.join(ohe)
dataset.head()

Survived  Pclass   Age  SibSp  Parch Embarked  male
0         0       3  22.0      1      0        S     1
1         1       1  38.0      1      0        C     0
2         1       3  26.0      0      0        S     0
3         1       1  35.0      1      0        S     0
4         0       3  35.0      0      0        S     1

In [162]:
#ohe = pd.get_dummies(dataset['Embarked'])
#dataset.drop('Embarked', axis = 1, inplace = True)
#dataset =  dataset.join(ohe)
#dataset.head()

In [163]:
#verificacion de NAs
dataset.isnull().values.any()

False

In [164]:
y = dataset.loc[:,'Survived']

In [165]:
dataset = dataset.drop(['Embarked'], axis=1)

In [166]:
dataset = dataset.drop(['Age'], axis=1)

In [167]:
dataset = dataset.drop(['Survived'], axis=1)

In [168]:
x = dataset

In [169]:
dataset

Pclass  SibSp  Parch  male
0         3      1      0     1
1         1      1      0     0
2         3      0      0     0
3         1      1      0     0
4         3      0      0     1
..      ...    ...    ...   ...
886       2      0      0     1
887       1      0      0     0
888       3      1      2     0
889       1      0      0     1
890       3      0      0     1

[891 rows x 4 columns]

In [171]:
x

Pclass  SibSp  Parch  male
0         3      1      0     1
1         1      1      0     0
2         3      0      0     0
3         1      1      0     0
4         3      0      0     1
..      ...    ...    ...   ...
886       2      0      0     1
887       1      0      0     0
888       3      1      2     0
889       1      0      0     1
890       3      0      0     1

[891 rows x 4 columns]

In [172]:
std_scaler = StandardScaler()
x = std_scaler.fit_transform(x)
x_train, x_test, y_train, y_test = train_test_split(x,y ,test_size =0.3 #,random_state = 2022
                                                    , shuffle = True)

In [173]:
inputs = x_train.shape[1]

# base secuencial 
clasificador = Sequential()

#primera capa oculta

clasificador.add(Dense(input_dim = inputs, units = 6 , activation = 'relu', kernel_initializer = 'uniform'))
                 
#segunda capa oculta
                 
clasificador.add(Dense(units =6, activation ='relu', kernel_initializer ='uniform'))

#capa de salida
                  
clasificador.add(Dense(units=1, activation = 'sigmoid', kernel_initializer = 'uniform'))

In [174]:
# parametros d eotpimizacion 

clasificador.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


#parametros de entrenamiento

clasificador.fit(x_train, y_train, batch_size = 25, epochs = 150)

Epoch 1/150
25/25 [==============================] - 0s 400us/step - loss: 0.6919 - accuracy: 0.6132
Epoch 2/150
25/25 [==============================] - 0s 400us/step - loss: 0.6892 - accuracy: 0.6148
Epoch 3/150
25/25 [==============================] - 0s 400us/step - loss: 0.6851 - accuracy: 0.6148
Epoch 4/150
25/25 [==============================] - 0s 360us/step - loss: 0.6768 - accuracy: 0.6148
Epoch 5/150
25/25 [==============================] - 0s 360us/step - loss: 0.6603 - accuracy: 0.6934
Epoch 6/150
25/25 [==============================] - 0s 400us/step - loss: 0.6352 - accuracy: 0.7881
Epoch 7/150
25/25 [==============================] - 0s 400us/step - loss: 0.6024 - accuracy: 0.7978
Epoch 8/150
25/25 [==============================] - 0s 400us/step - loss: 0.5667 - accuracy: 0.8122
Epoch 9/150
25/25 [==============================] - 0s 400us/step - loss: 0.5343 - accuracy: 0.8170
Epoch 10/150
25/25 [==============================] - 0s 400us/step - loss: 0.5073 - accura

25/25 [==============================] - 0s 400us/step - loss: 0.4296 - accuracy: 0.8138
Epoch 82/150
25/25 [==============================] - 0s 400us/step - loss: 0.4294 - accuracy: 0.8138
Epoch 83/150
25/25 [==============================] - 0s 400us/step - loss: 0.4294 - accuracy: 0.8138
Epoch 84/150
25/25 [==============================] - 0s 400us/step - loss: 0.4297 - accuracy: 0.8138
Epoch 85/150
25/25 [==============================] - 0s 440us/step - loss: 0.4297 - accuracy: 0.8138
Epoch 86/150
25/25 [==============================] - 0s 400us/step - loss: 0.4290 - accuracy: 0.8138
Epoch 87/150
25/25 [==============================] - 0s 400us/step - loss: 0.4289 - accuracy: 0.8138
Epoch 88/150
25/25 [==============================] - 0s 400us/step - loss: 0.4297 - accuracy: 0.8138
Epoch 89/150
25/25 [==============================] - 0s 400us/step - loss: 0.4291 - accuracy: 0.8138
Epoch 90/150
25/25 [==============================] - 0s 400us/step - loss: 0.4288 - accuracy: 

In [175]:
#Guardar el modelo

path = 'D:/Jhonnatan/Documents/MAESTRIA DATA SCIENCE/3er Trimestre/Statical Learning III/TAREAS/titanic/'
clasificador.save(path+ '6_6_sig_outAdam.h5')


In [235]:
# parametros d eotpimizacion 

clasificador.compile(optimizer = 'RMSprop', loss = 'binary_crossentropy', metrics = ['accuracy'])


#parametros de entrenamiento

clasificador.fit(x_train, y_train, batch_size = 25, epochs = 150)

Epoch 1/150
25/25 [==============================] - 0s 400us/step - loss: 0.4263 - accuracy: 0.8138
Epoch 2/150
25/25 [==============================] - 0s 360us/step - loss: 0.4257 - accuracy: 0.8122
Epoch 3/150
25/25 [==============================] - 0s 400us/step - loss: 0.4257 - accuracy: 0.8122
Epoch 4/150
25/25 [==============================] - 0s 360us/step - loss: 0.4255 - accuracy: 0.8138
Epoch 5/150
25/25 [==============================] - 0s 360us/step - loss: 0.4255 - accuracy: 0.8122
Epoch 6/150
25/25 [==============================] - 0s 400us/step - loss: 0.4260 - accuracy: 0.8138
Epoch 7/150
25/25 [==============================] - 0s 400us/step - loss: 0.4255 - accuracy: 0.8138
Epoch 8/150
25/25 [==============================] - 0s 360us/step - loss: 0.4254 - accuracy: 0.8138
Epoch 9/150
25/25 [==============================] - 0s 400us/step - loss: 0.4253 - accuracy: 0.8122
Epoch 10/150
25/25 [==============================] - 0s 360us/step - loss: 0.4255 - accura

25/25 [==============================] - 0s 400us/step - loss: 0.4246 - accuracy: 0.8138
Epoch 82/150
25/25 [==============================] - 0s 400us/step - loss: 0.4247 - accuracy: 0.8138
Epoch 83/150
25/25 [==============================] - 0s 440us/step - loss: 0.4245 - accuracy: 0.8138
Epoch 84/150
25/25 [==============================] - 0s 400us/step - loss: 0.4247 - accuracy: 0.8122
Epoch 85/150
25/25 [==============================] - 0s 400us/step - loss: 0.4245 - accuracy: 0.8154
Epoch 86/150
25/25 [==============================] - 0s 400us/step - loss: 0.4246 - accuracy: 0.8154
Epoch 87/150
25/25 [==============================] - 0s 400us/step - loss: 0.4243 - accuracy: 0.8138
Epoch 88/150
25/25 [==============================] - 0s 360us/step - loss: 0.4239 - accuracy: 0.8122
Epoch 89/150
25/25 [==============================] - 0s 400us/step - loss: 0.4247 - accuracy: 0.8170
Epoch 90/150
25/25 [==============================] - 0s 400us/step - loss: 0.4246 - accuracy: 

In [236]:
#Guardar el modelo

path = 'D:/Jhonnatan/Documents/MAESTRIA DATA SCIENCE/3er Trimestre/Statical Learning III/TAREAS/titanic/'
clasificador.save(path+ '6_6_sig_outRMSprop.h5')

In [237]:
# parametros d eotpimizacion 

clasificador.compile(optimizer = 'SGD', loss = 'binary_crossentropy', metrics = ['accuracy'])


#parametros de entrenamiento

clasificador.fit(x_train, y_train, batch_size = 25, epochs = 150)

Epoch 1/150
25/25 [==============================] - 0s 360us/step - loss: 0.4236 - accuracy: 0.8138
Epoch 2/150
25/25 [==============================] - 0s 360us/step - loss: 0.4233 - accuracy: 0.8138
Epoch 3/150
25/25 [==============================] - 0s 360us/step - loss: 0.4235 - accuracy: 0.8154
Epoch 4/150
25/25 [==============================] - 0s 360us/step - loss: 0.4235 - accuracy: 0.8154
Epoch 5/150
25/25 [==============================] - 0s 360us/step - loss: 0.4236 - accuracy: 0.8154
Epoch 6/150
25/25 [==============================] - 0s 400us/step - loss: 0.4237 - accuracy: 0.8138
Epoch 7/150
25/25 [==============================] - 0s 360us/step - loss: 0.4233 - accuracy: 0.8154
Epoch 8/150
25/25 [==============================] - 0s 360us/step - loss: 0.4234 - accuracy: 0.8154
Epoch 9/150
25/25 [==============================] - 0s 360us/step - loss: 0.4234 - accuracy: 0.8138
Epoch 10/150
25/25 [==============================] - 0s 400us/step - loss: 0.4234 - accura

25/25 [==============================] - 0s 360us/step - loss: 0.4231 - accuracy: 0.8154
Epoch 82/150
25/25 [==============================] - 0s 480us/step - loss: 0.4233 - accuracy: 0.8154
Epoch 83/150
25/25 [==============================] - 0s 360us/step - loss: 0.4232 - accuracy: 0.8154
Epoch 84/150
25/25 [==============================] - 0s 360us/step - loss: 0.4233 - accuracy: 0.8154
Epoch 85/150
25/25 [==============================] - 0s 360us/step - loss: 0.4232 - accuracy: 0.8154
Epoch 86/150
25/25 [==============================] - 0s 400us/step - loss: 0.4232 - accuracy: 0.8154
Epoch 87/150
25/25 [==============================] - 0s 360us/step - loss: 0.4232 - accuracy: 0.8154
Epoch 88/150
25/25 [==============================] - 0s 400us/step - loss: 0.4233 - accuracy: 0.8154
Epoch 89/150
25/25 [==============================] - 0s 360us/step - loss: 0.4234 - accuracy: 0.8154
Epoch 90/150
25/25 [==============================] - 0s 400us/step - loss: 0.4231 - accuracy: 

In [238]:
#Guardar el modelo

path = 'D:/Jhonnatan/Documents/MAESTRIA DATA SCIENCE/3er Trimestre/Statical Learning III/TAREAS/titanic/'
clasificador.save(path+ '6_6_sig_outSGD.h5')

In [240]:
# parametros d eotpimizacion 

clasificador.compile(optimizer = 'Adamax', loss = 'binary_crossentropy', metrics = ['accuracy'])


#parametros de entrenamiento

clasificador.fit(x_train, y_train, batch_size = 25, epochs = 150)

Epoch 1/150
25/25 [==============================] - 0s 440us/step - loss: 0.4233 - accuracy: 0.8154
Epoch 2/150
25/25 [==============================] - 0s 400us/step - loss: 0.4226 - accuracy: 0.8154
Epoch 3/150
25/25 [==============================] - 0s 360us/step - loss: 0.4226 - accuracy: 0.8154
Epoch 4/150
25/25 [==============================] - 0s 360us/step - loss: 0.4225 - accuracy: 0.8154
Epoch 5/150
25/25 [==============================] - 0s 400us/step - loss: 0.4225 - accuracy: 0.8154
Epoch 6/150
25/25 [==============================] - 0s 480us/step - loss: 0.4224 - accuracy: 0.8154
Epoch 7/150
25/25 [==============================] - 0s 400us/step - loss: 0.4224 - accuracy: 0.8154
Epoch 8/150
25/25 [==============================] - 0s 360us/step - loss: 0.4224 - accuracy: 0.8154
Epoch 9/150
25/25 [==============================] - 0s 400us/step - loss: 0.4224 - accuracy: 0.8154
Epoch 10/150
25/25 [==============================] - 0s 360us/step - loss: 0.4226 - accura

25/25 [==============================] - 0s 400us/step - loss: 0.4224 - accuracy: 0.8154
Epoch 79/150
25/25 [==============================] - 0s 360us/step - loss: 0.4224 - accuracy: 0.8154
Epoch 80/150
25/25 [==============================] - 0s 400us/step - loss: 0.4224 - accuracy: 0.8154
Epoch 81/150
25/25 [==============================] - 0s 400us/step - loss: 0.4223 - accuracy: 0.8154
Epoch 82/150
25/25 [==============================] - 0s 360us/step - loss: 0.4222 - accuracy: 0.8154
Epoch 83/150
25/25 [==============================] - 0s 360us/step - loss: 0.4223 - accuracy: 0.8154
Epoch 84/150
25/25 [==============================] - 0s 400us/step - loss: 0.4223 - accuracy: 0.8154
Epoch 85/150
25/25 [==============================] - 0s 400us/step - loss: 0.4223 - accuracy: 0.8154
Epoch 86/150
25/25 [==============================] - 0s 400us/step - loss: 0.4223 - accuracy: 0.8154
Epoch 87/150
25/25 [==============================] - 0s 360us/step - loss: 0.4222 - accuracy: 

In [241]:
#Guardar el modelo

path = 'D:/Jhonnatan/Documents/MAESTRIA DATA SCIENCE/3er Trimestre/Statical Learning III/TAREAS/titanic/'
clasificador.save(path+ '6_6_sig_outAdamax.h5')

In [244]:
modelo1 = '6_6_sig_outAdam.h5'
modelo2 = '6_6_sig_outRMSprop.h5'
modelo3 ='6_6_sig_outSGD.h5'
modelo4 = '6_6_sig_outAdamax.h5'
#cargamos a la read 
path = 'D:/Jhonnatan/Documents/MAESTRIA DATA SCIENCE/3er Trimestre/Statical Learning III/TAREAS/titanic/'

new_model1 = keras.models.load_model(path+modelo1)
new_model2 = keras.models.load_model(path+modelo2)
new_model3 = keras.models.load_model(path+modelo3)
new_model4 = keras.models.load_model(path+modelo4)

In [263]:
y_pred = new_model3.predict(x_test)
y_pred

array([[0.9339651 ],
       [0.9803189 ],
       [0.9818227 ],
       [0.9339651 ],
       [0.14074898],
       [0.14074898],
       [0.33595204],
       [0.4309366 ],
       [0.1476483 ],
       [0.6220081 ],
       [0.15714076],
       [0.58740664],
       [0.14074898],
       [0.41338617],
       [0.9803189 ],
       [0.14890668],
       [0.14074898],
       [0.6220081 ],
       [0.1476483 ],
       [0.2578885 ],
       [0.6220081 ],
       [0.10536507],
       [0.9840818 ],
       [0.14074898],
       [0.14074898],
       [0.93979   ],
       [0.2578885 ],
       [0.2578885 ],
       [0.05841845],
       [0.58740664],
       [0.14074892],
       [0.25788844],
       [0.10536507],
       [0.9840818 ],
       [0.57207084],
       [0.14074898],
       [0.9803189 ],
       [0.9339651 ],
       [0.14074898],
       [0.6220081 ],
       [0.14074898],
       [0.3768114 ],
       [0.6220081 ],
       [0.27354223],
       [0.10536507],
       [0.14074898],
       [0.9840818 ],
       [0.928

In [264]:
y_pred = (y_pred >= 0.5)
y_pred

array([[ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [

In [269]:
accuracy_score(y_test, y_pred)

0.7985074626865671

In [270]:
dataset_test = pd.read_csv("D:/Jhonnatan/Documents/MAESTRIA DATA SCIENCE/3er Trimestre/Statical Learning III/TAREAS/titanic/test.csv")
dataset_test.head()


PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [271]:
dataset_test = dataset_test[["Pclass", "Sex", "Age", "SibSp","Parch"]]

In [272]:
#verificacion de NAs
dataset_test.isnull().values.any()

True

In [273]:
moda_edad_test = dataset_test.median()
moda_edad_test[["Age"]]

<ipython-input-273-c534cb54d712>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  moda_edad_test = dataset_test.median()


Age    27.0
dtype: float64

In [274]:
dataset_test = dataset_test.fillna(27)
dataset_test

Pclass     Sex   Age  SibSp  Parch
0         3    male  34.5      0      0
1         3  female  47.0      1      0
2         2    male  62.0      0      0
3         3    male  27.0      0      0
4         3  female  22.0      1      1
..      ...     ...   ...    ...    ...
413       3    male  27.0      0      0
414       1  female  39.0      0      0
415       3    male  38.5      0      0
416       3    male  27.0      0      0
417       3    male  27.0      1      1

[418 rows x 5 columns]

In [275]:
ohe_test = pd.get_dummies(dataset_test['Sex'],drop_first = True)
dataset_test.drop('Sex', axis = 1, inplace = True)
dataset_test =  dataset_test.join(ohe_test)
dataset_test.head()

Pclass   Age  SibSp  Parch  male
0       3  34.5      0      0     1
1       3  47.0      1      0     0
2       2  62.0      0      0     1
3       3  27.0      0      0     1
4       3  22.0      1      1     0

In [276]:
dataset_test = dataset_test.drop(['Age'], axis=1)

In [248]:
path = 'D:/Jhonnatan/Documents/MAESTRIA DATA SCIENCE/3er Trimestre/Statical Learning III/TAREAS/titanic/'
new_model = keras.models.load_model(path+ '6_6_sig_out.h5')


OSError: SavedModel file does not exist at: D:/Jhonnatan/Documents/MAESTRIA DATA SCIENCE/3er Trimestre/Statical Learning III/TAREAS/titanic/6_6_sig_out.h5/{saved_model.pbtxt|saved_model.pb}

In [277]:
std_scaler = StandardScaler()
dataset_test = std_scaler.fit_transform(dataset_test)

In [278]:
prediccion = new_model2.predict(dataset_test)
prediccion
#prediccion_df = {'Survived' : [prediccion]}

array([[0.14729434],
       [0.5512472 ],
       [0.11174574],
       [0.14729434],
       [0.5520277 ],
       [0.14729434],
       [0.59422576],
       [0.36561096],
       [0.59422576],
       [0.1099295 ],
       [0.14729434],
       [0.23770344],
       [0.9831046 ],
       [0.16770053],
       [0.9831046 ],
       [0.9185252 ],
       [0.11174574],
       [0.14729434],
       [0.5512472 ],
       [0.59422576],
       [0.38077357],
       [0.37511513],
       [0.9794677 ],
       [0.39475513],
       [0.96220076],
       [0.13705146],
       [0.9814547 ],
       [0.14729434],
       [0.23770344],
       [0.1099295 ],
       [0.16770053],
       [0.13230199],
       [0.36579287],
       [0.36579287],
       [0.38077357],
       [0.14729434],
       [0.59422576],
       [0.59422576],
       [0.14729434],
       [0.14729434],
       [0.37511513],
       [0.23770344],
       [0.14729434],
       [0.9281945 ],
       [0.9831046 ],
       [0.14729434],
       [0.23770344],
       [0.147

In [279]:
rounded = [np.round(x) for x in prediccion]

In [280]:
rounded

[array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], d

In [290]:
dataset_test2 = pd.read_csv("D:/Jhonnatan/Documents/MAESTRIA DATA SCIENCE/3er Trimestre/Statical Learning III/TAREAS/titanic/test.csv")
dataset_test2.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [291]:
id_cliente = dataset_test2.loc[:,'PassengerId']
df = pd.DataFrame (id_cliente)
df

PassengerId
0            892
1            893
2            894
3            895
4            896
..           ...
413         1305
414         1306
415         1307
416         1308
417         1309

[418 rows x 1 columns]

In [292]:

df2 = pd.DataFrame (rounded)
df2

0
0    0.0
1    1.0
2    0.0
3    0.0
4    1.0
..   ...
413  0.0
414  1.0
415  0.0
416  0.0
417  0.0

[418 rows x 1 columns]

In [293]:
df =  df.join(df2)

In [294]:
df

PassengerId    0
0            892  0.0
1            893  1.0
2            894  0.0
3            895  0.0
4            896  1.0
..           ...  ...
413         1305  0.0
414         1306  1.0
415         1307  0.0
416         1308  0.0
417         1309  0.0

[418 rows x 2 columns]

In [296]:
df.to_csv('myfile3.csv')

In [287]:
np.savetxt('myfile3.csv', array_3, delimiter=';')

In [223]:
import csv

header = ['PassengerId', 'Survived']

with open('test1.csv', 'w', encoding='UTF8', newline='') as f:
    writer = csv.writer(f)

    # write the header
    writer.writerow(header)

    # write multiple rows
    writer.writerows(array_3)

Error: iterable expected, not numpy.float64

In [50]:
dataset_test =  dataset_test.join(prediccion)
dataset_test

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [45]:
clients = {'first_name' : ['Oralie' ,'Imojean' ,'Michele', 'Ailbert', 'Stevy'],
           'last_name' : ['Fidgeon' ,'Benet' ,'Woodlands', 'Risdale', 'MacGorman'],
           'age' : [30 ,21 ,29 ,22, 24]}
clients = pd.DataFrame(clients, columns = ['first_name', 'last_name', 'age'])
clients

first_name  last_name  age
0     Oralie    Fidgeon   30
1    Imojean      Benet   21
2    Michele  Woodlands   29
3    Ailbert    Risdale   22
4      Stevy  MacGorman   24